// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl72Tz5ZGFazeQX9DtL-LjZrvhrdxHB7U',
    appId: '1:194450397628:web:dab2b89d58375bc67433b9',
    messagingSenderId: '194450397628',
    projectId: 'modul-3-6d7a0',
    authDomain: 'modul-3-6d7a0.firebaseapp.com',
    storageBucket: 'modul-3-6d7a0.appspot.com',
    measurementId: 'G-D8ZGZ1L972',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy05c6Dhfq0L49szw06ze2x5jJlJHrBjA',
    appId: '1:194450397628:android:db66704f1b84014e7433b9',
    messagingSenderId: '194450397628',
    projectId: 'modul-3-6d7a0',
    storageBucket: 'modul-3-6d7a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD076O74y6yqokra4634xZw1Kd1dTFziq8',
    appId: '1:194450397628:ios:18da317d0be394c07433b9',
    messagingSenderId: '194450397628',
    projectId: 'modul-3-6d7a0',
    storageBucket: 'modul-3-6d7a0.appspot.com',
    iosBundleId: 'com.example.codelab',
  );
}
